### PR TITLE
Updated to PSR4

### PR DESCRIPTION
**Pull request by schtom21**
On my working on the module, I have seen that there are no tests anymore. Is there a reason for this?

### CODE REVIEW

**Comment by dakala** [comment]
@schtom21, thanks for this. Actually the PSR4 changes have been made locally only not pushed yet.  Will push later today. 

Can't recall why I removed the tests but it was meant to be temporary, there will be tests.

**Comment by Berdir** [comment]
@dakala Note that there some additional fixes in here, like the form class rename.

**Comment by dakala** [comment]
The changes I've made make poll compatible with alpha-12, if that's what you mean. I'll push shortly.

**Comment by dakala** [comment]
I've just pushed my changes please. @schtom21, another PR possibly?  Sorry guys.

**Comment by dakala** [comment]
@schtom21: https://github.com/md-systems/poll/commit/0883f78e7bc0d70846f4159cd31e6f8d29549e2b - Change getBuildDefaults() to view() and make the method public in PollViewBuilder.php is definitely not part of my push. 

And if you've got the tests, could you replace them please?

**Comment by schtom21** [comment]
@dakala I changed the PollViewBuilder.php File back. I think the view() method should work fine.

**Comment by Berdir** [comment]
We will create a new pull request and work on re-adding the tests based on what's currently in the d.o poll repository

**Comment by dakala** [comment]
The poll repository on d.o. is very old. This is the most up-to-date poll module

**Comment by Berdir** [comment]
@dakala Yes, we're aware of that, but we checked the history and when the tests were removed, and nothing changed in them compared to the d.o repository excpet an incorrect block => Block rename. So it doesn't really matter but we will start with the d.o version of the tests, as that rename was wrong (it renamed things like the block module name)

**Comment by dakala** [comment]
@Berdir That's cool :+1:

**Comment by typhonius** [comment]
I'm going to review and pull across from here to d.o at some point soon so we can keep that one up to date.

**Pull request merged**
